name: C/C++ CI

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sh ./scripts/configure
    - name: build
      run: sh ./scripts/build
    - name: RunningTests
      run: cd CBuild ; ./mini_nginx_tests
    - uses: actions/upload-artifact@v4
      with:
        name: MiniNginx-Ubuntu
        path: CBuild/