name: Deploy to MiniNgnix

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的写入权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # 关键权限保持
    
    - name: No ManDB pls
      run: sudo apt remove --purge man-db

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Generate Docs
      run: |
        doxygen Doxyfile
        cp Doxygen/open.png Doxygen/clopen.png
        cp Doxygen/closed.png Doxygen/clclosed.png
        mkdir -p public/MiniNginx
        cp -R Doxygen/* public/MiniNginx/

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true  # 强制清空历史
        keep_files: false
